from datetime import datetime, timedelta

_BASE = datetime(2020, 4, 7)

def ts(days: int, hours: int = 0) -> str:
    return (_BASE + timedelta(days=days, hours=hours)).isoformat()

CHARACTERS = [
    {
        "id": "ayanokoji",
        "name": "Kiyotaka Ayanokoji",
        "class_name": "D",
        "description": "Product of the White Room. Conceals extraordinary cognitive capability beneath deliberate mediocrity. Every human interaction is a variable to be solved. Views social dynamics as equations with predictable outputs.",
        "strategic_tendencies": ["deception", "observation", "long_term_planning", "proxy_control", "calculated_restraint"],
        "trust_level": 0.12,
        "influence_score": 0.97,
        "faction": "White Room",
        "personality_summary": "An absolute strategist who treats relationships as mathematical instruments. Operates from the shadows with perfect information control. His true capability remains unknown to all.",
    },
    {
        "id": "horikita",
        "name": "Suzune Horikita",
        "class_name": "D",
        "description": "Driven by obsessive ambition to reach Class A. Analytically precise, emotionally rigid, and painfully direct. Struggles with trust but shows hidden capacity for genuine growth.",
        "strategic_tendencies": ["discipline", "direct_confrontation", "academic_excellence", "emotional_suppression", "growth"],
        "trust_level": 0.58,
        "influence_score": 0.72,
        "faction": "Class D",
        "personality_summary": "Rigid perfectionist whose singular focus on advancement blinds her to relational nuance. Gradually learns that people are assets, not obstacles.",
    },
    {
        "id": "kushida",
        "name": "Kikyou Kushida",
        "class_name": "D",
        "description": "Constructed an elaborate social persona of universal friendliness concealing dark psychology. Her true self is consumed by jealousy and the pathological need for social supremacy.",
        "strategic_tendencies": ["social_manipulation", "information_gathering", "charm_exploitation", "sabotage", "facade_maintenance"],
        "trust_level": 0.06,
        "influence_score": 0.68,
        "faction": "Class D",
        "personality_summary": "A perfect social weapon disguised as the class sweetheart. Beneath warmth lies calculated malice. The most dangerous smile in the building.",
    },
    {
        "id": "hirata",
        "name": "Yosuke Hirata",
        "class_name": "D",
        "description": "Natural social leader who maintains class harmony through warmth and mediation. His strength is genuine consensus-building, though his idealism can be exploited.",
        "strategic_tendencies": ["alliance", "mediation", "loyalty", "social_cohesion", "empathy"],
        "trust_level": 0.82,
        "influence_score": 0.65,
        "faction": "Class D",
        "personality_summary": "Genuine connector and class anchor. His trust is a strategic liability and strength simultaneously.",
    },
    {
        "id": "sudo",
        "name": "Ken Sudo",
        "class_name": "D",
        "description": "Impulsive and combative but fiercely loyal. His emotional volatility makes him a liability in subtle conflicts but a powerful asset in direct confrontation.",
        "strategic_tendencies": ["direct_confrontation", "loyalty", "impulsiveness", "physical_dominance", "growth"],
        "trust_level": 0.70,
        "influence_score": 0.45,
        "faction": "Class D",
        "personality_summary": "Raw power with emerging loyalty. Useful as a blunt instrument; unreliable as a subtle one.",
    },
    {
        "id": "sakura",
        "name": "Airi Sakura",
        "class_name": "D",
        "description": "Shy and seemingly fragile, but possesses strong observational skills and quiet resilience. Her low social profile makes her an effective intelligence gatherer.",
        "strategic_tendencies": ["observation", "loyalty", "information_gathering", "concealment", "resilience"],
        "trust_level": 0.75,
        "influence_score": 0.38,
        "faction": "Class D",
        "personality_summary": "Underestimated asset. Her invisibility is her primary strategic advantage.",
    },
    {
        "id": "hasebe",
        "name": "Haruka Hasebe",
        "class_name": "D",
        "description": "Free-spirited and social, loyal to her close circle. Not a strategic thinker but highly attuned to social dynamics within her immediate network.",
        "strategic_tendencies": ["loyalty", "social_cohesion", "intuition", "alliance", "protectiveness"],
        "trust_level": 0.78,
        "influence_score": 0.42,
        "faction": "Class D",
        "personality_summary": "Warm social anchor for her inner circle. Reliable ally; limited strategic range.",
    },
    {
        "id": "koenji",
        "name": "Rokusuke Koenji",
        "class_name": "D",
        "description": "Absolute narcissist and true independent. Refuses all alliances and obligations. Possesses elite capability that he deploys only for personal benefit.",
        "strategic_tendencies": ["absolute_independence", "self_optimization", "calculated_neutrality", "concealed_ability", "contempt"],
        "trust_level": 0.15,
        "influence_score": 0.60,
        "faction": "Independent",
        "personality_summary": "An island of absolute self-interest. Neither ally nor enemy. His potential is incalculable and his motivations opaque.",
    },
    {
        "id": "yukimura",
        "name": "Teruhiko Yukimura",
        "class_name": "D",
        "description": "Studious and analytically sharp. Underestimated due to lack of social capital. A reliable ally when his intellectual skills are engaged.",
        "strategic_tendencies": ["academic_excellence", "loyalty", "discipline", "analytical_thinking", "introversion"],
        "trust_level": 0.68,
        "influence_score": 0.40,
        "faction": "Class D",
        "personality_summary": "Reliable academic asset. Low social influence but high situational value in knowledge-based conflicts.",
    },
    {
        "id": "shiranami",
        "name": "Chihiro Shiranami",
        "class_name": "D",
        "description": "Quiet and observant. Knows more than she reveals. Her silence and peripheral positioning make her an effective information node.",
        "strategic_tendencies": ["observation", "concealment", "information_gathering", "neutrality", "patience"],
        "trust_level": 0.55,
        "influence_score": 0.35,
        "faction": "Class D",
        "personality_summary": "The overlooked watcher. Possesses intelligence others discard. Her neutrality is a deliberate strategy.",
    },
    {
        "id": "sato",
        "name": "Maya Sato",
        "class_name": "D",
        "description": "Perceptive and socially connected. Bridges different Class D factions. Her emotional intelligence grants access to information most strategists miss.",
        "strategic_tendencies": ["social_cohesion", "intuition", "alliance", "loyalty", "observation"],
        "trust_level": 0.72,
        "influence_score": 0.44,
        "faction": "Class D",
        "personality_summary": "Emotional intelligence as strategic capital. Her bridge role makes her an undervalued network hub.",
    },
    {
        "id": "ichinose",
        "name": "Honami Ichinose",
        "class_name": "B",
        "description": "Class B leader. Warm, popular, and extraordinarily competent at building genuine loyalty. Conceals a secret that could shatter her constructed image.",
        "strategic_tendencies": ["alliance", "loyalty", "social_influence", "protectiveness", "genuine_leadership"],
        "trust_level": 0.85,
        "influence_score": 0.80,
        "faction": "Class B",
        "personality_summary": "The most beloved student in school. Her warmth is genuine—which is both her greatest strength and her deepest vulnerability.",
    },
    {
        "id": "kanzaki",
        "name": "Ryuji Kanzaki",
        "class_name": "B",
        "description": "Ichinose's principal strategist. Calculating and controlled. His loyalty to Ichinose is absolute; his methods are flexible.",
        "strategic_tendencies": ["analytical_thinking", "loyalty", "long_term_planning", "protectiveness", "discipline"],
        "trust_level": 0.78,
        "influence_score": 0.62,
        "faction": "Class B",
        "personality_summary": "The architect behind Ichinose's success. Operates best in a supporting strategic role.",
    },
    {
        "id": "sakagami",
        "name": "Kazuma Sakagami",
        "class_name": "B",
        "description": "Loyal Class B member and reliable enforcer of Ichinose's coalition. Strong interpersonal skills and commitment to the group mission.",
        "strategic_tendencies": ["loyalty", "alliance", "social_cohesion", "protectiveness", "direct_confrontation"],
        "trust_level": 0.80,
        "influence_score": 0.50,
        "faction": "Class B",
        "personality_summary": "Dependable cornerstone of Class B unity. His loyalty is non-negotiable.",
    },
    {
        "id": "ryuen",
        "name": "Kakeru Ryuen",
        "class_name": "C",
        "description": "Rules Class C through fear and absolute dominance. Brutally intelligent and strategically ruthless. Despises weakness and exploits it without mercy.",
        "strategic_tendencies": ["intimidation", "manipulation", "information_control", "ruthlessness", "dominance"],
        "trust_level": 0.20,
        "influence_score": 0.84,
        "faction": "Class C",
        "personality_summary": "The tyrant of Class C. Controls through fear but possesses genuine strategic genius beneath the violence.",
    },
    {
        "id": "ibuki",
        "name": "Mio Ibuki",
        "class_name": "C",
        "description": "Ryuen's primary enforcer. Physically dominant and aggressively loyal—to a point. Harbors private doubts about Ryuen's leadership methods.",
        "strategic_tendencies": ["direct_confrontation", "loyalty", "physical_dominance", "intimidation", "suppressed_doubt"],
        "trust_level": 0.35,
        "influence_score": 0.55,
        "faction": "Class C",
        "personality_summary": "Controlled aggression in service of a questionable master. Her private doubts are a strategic opening.",
    },
    {
        "id": "yagami",
        "name": "Sho Yagami",
        "class_name": "C",
        "description": "Ryuen's informant and sycophant. Highly skilled at social infiltration but fundamentally motivated by self-preservation.",
        "strategic_tendencies": ["social_manipulation", "information_gathering", "sycophancy", "self_preservation", "facade_maintenance"],
        "trust_level": 0.25,
        "influence_score": 0.48,
        "faction": "Class C",
        "personality_summary": "A spider who tells its handler only what it wants to hear. Self-interest is his true allegiance.",
    },
    {
        "id": "albert",
        "name": "Albert Yamada",
        "class_name": "C",
        "description": "Ryuen's physical enforcer. Imposing presence and total loyalty. Limited strategic role but essential for maintaining Ryuen's control through physical intimidation.",
        "strategic_tendencies": ["physical_dominance", "loyalty", "intimidation", "direct_confrontation", "protectiveness"],
        "trust_level": 0.45,
        "influence_score": 0.42,
        "faction": "Class C",
        "personality_summary": "Blunt instrument of absolute loyalty. Effective in the role he occupies.",
    },
    {
        "id": "hondou",
        "name": "Ryotaro Hondou",
        "class_name": "C",
        "description": "Independent thinker within Class C. Follows Ryuen's direction but maintains private reservations. A potential defection risk under the right conditions.",
        "strategic_tendencies": ["independent_thinking", "loyalty", "observation", "calculated_compliance", "suppressed_doubt"],
        "trust_level": 0.50,
        "influence_score": 0.40,
        "faction": "Class C",
        "personality_summary": "A crack in the Class C monolith. His independent thinking makes him both useful and dangerous to Ryuen.",
    },
    {
        "id": "sakayanagi",
        "name": "Arisu Sakayanagi",
        "class_name": "A",
        "description": "Class A leader. Prodigious intellect concealed behind a disarming smile. Uses wheelchair; physical limitation is irrelevant to her absolute strategic superiority.",
        "strategic_tendencies": ["manipulation", "long_term_planning", "information_control", "psychological_dominance", "facade_maintenance"],
        "trust_level": 0.22,
        "influence_score": 0.92,
        "faction": "Class A (Sakayanagi)",
        "personality_summary": "The most dangerous strategist in the school. Plays three moves ahead while appearing to smile at the present.",
    },
    {
        "id": "hashimoto",
        "name": "Masayoshi Hashimoto",
        "class_name": "A",
        "description": "Sakayanagi's primary social operator. Skilled at relationship manipulation and information extraction through apparent friendliness.",
        "strategic_tendencies": ["social_manipulation", "charm_exploitation", "information_gathering", "loyalty", "facade_maintenance"],
        "trust_level": 0.30,
        "influence_score": 0.58,
        "faction": "Class A (Sakayanagi)",
        "personality_summary": "Sakayanagi's smiling knife. Executes social operations with casual precision.",
    },
    {
        "id": "katsuragi",
        "name": "Kohei Katsuragi",
        "class_name": "A",
        "description": "Former Class A leader displaced by Sakayanagi. Rigid adherence to rule-based strategy. Struggles against more flexible opponents.",
        "strategic_tendencies": ["discipline", "rule_based_strategy", "direct_confrontation", "pride", "analytical_thinking"],
        "trust_level": 0.60,
        "influence_score": 0.55,
        "faction": "Class A (Katsuragi)",
        "personality_summary": "A general who fights yesterday's wars. His rigidity makes him predictable; his discipline makes him reliable.",
    },
    {
        "id": "kiriyama",
        "name": "Asuka Kiriyama",
        "class_name": "A",
        "description": "Class A member with calculated loyalty split between the Sakayanagi and Katsuragi factions. Navigates internal conflict through strategic neutrality.",
        "strategic_tendencies": ["calculated_neutrality", "observation", "alliance", "long_term_planning", "adaptability"],
        "trust_level": 0.52,
        "influence_score": 0.48,
        "faction": "Class A (Katsuragi)",
        "personality_summary": "A bridge figure in an internally divided class. Her position grants access to both camps.",
    },
    {
        "id": "chabashira",
        "name": "Sae Chabashira",
        "class_name": "Teacher",
        "description": "Class D homeroom teacher with a hidden past linked to the school's true system. Applies unusual pressure specifically to Ayanokoji. Her motivations remain opaque.",
        "strategic_tendencies": ["information_control", "observation", "authority", "manipulation", "concealment"],
        "trust_level": 0.28,
        "influence_score": 0.70,
        "faction": "Faculty",
        "personality_summary": "A teacher who knows too much and reveals too little. Her interest in Ayanokoji is not academic.",
    },
    {
        "id": "nagumo",
        "name": "Miyabi Nagumo",
        "class_name": "Council",
        "description": "Student Council President of the second year. Aggressively ambitious and politically sophisticated. Establishes dominance through structural control of school resources.",
        "strategic_tendencies": ["political_dominance", "manipulation", "information_control", "ruthlessness", "long_term_planning"],
        "trust_level": 0.18,
        "influence_score": 0.88,
        "faction": "Student Council",
        "personality_summary": "Political predator operating at institutional scale. Controls systems, not just individuals.",
    },
]

RELATIONSHIPS = [
    # Ayanokoji's network
    {"source": "ayanokoji", "target": "horikita",   "type": "MANIPULATES",    "weight": 0.88, "trust": 0.42, "confidence": 0.95, "timestamp": ts(5)},
    {"source": "ayanokoji", "target": "kushida",    "type": "DECEIVES",       "weight": 0.92, "trust": 0.05, "confidence": 0.98, "timestamp": ts(10)},
    {"source": "ayanokoji", "target": "ryuen",      "type": "RIVALS",         "weight": 0.82, "trust": 0.28, "confidence": 0.90, "timestamp": ts(60)},
    {"source": "ayanokoji", "target": "sakayanagi", "type": "RIVALS",         "weight": 0.94, "trust": 0.32, "confidence": 0.92, "timestamp": ts(90)},
    {"source": "ayanokoji", "target": "ichinose",   "type": "INFLUENCES",     "weight": 0.70, "trust": 0.58, "confidence": 0.85, "timestamp": ts(30)},
    {"source": "ayanokoji", "target": "hirata",     "type": "INFLUENCES",     "weight": 0.65, "trust": 0.68, "confidence": 0.80, "timestamp": ts(15)},
    {"source": "ayanokoji", "target": "sudo",       "type": "PROTECTS",       "weight": 0.78, "trust": 0.62, "confidence": 0.88, "timestamp": ts(20)},
    {"source": "ayanokoji", "target": "chabashira", "type": "DISTRUSTS",      "weight": 0.55, "trust": 0.22, "confidence": 0.82, "timestamp": ts(2)},
    {"source": "ayanokoji", "target": "koenji",     "type": "INFLUENCES",     "weight": 0.50, "trust": 0.38, "confidence": 0.70, "timestamp": ts(45)},
    {"source": "ayanokoji", "target": "nagumo",     "type": "RIVALS",         "weight": 0.78, "trust": 0.18, "confidence": 0.85, "timestamp": ts(180)},
    {"source": "ayanokoji", "target": "sakura",     "type": "PROTECTS",       "weight": 0.62, "trust": 0.72, "confidence": 0.78, "timestamp": ts(25)},
    {"source": "ayanokoji", "target": "hashimoto",  "type": "DISTRUSTS",      "weight": 0.60, "trust": 0.20, "confidence": 0.82, "timestamp": ts(92)},
    {"source": "ayanokoji", "target": "kanzaki",    "type": "INFLUENCES",     "weight": 0.55, "trust": 0.50, "confidence": 0.75, "timestamp": ts(35)},
    # Horikita
    {"source": "horikita", "target": "sudo",       "type": "PROTECTS",        "weight": 0.72, "trust": 0.74, "confidence": 0.88, "timestamp": ts(18)},
    {"source": "horikita", "target": "kushida",    "type": "DISTRUSTS",       "weight": 0.85, "trust": 0.12, "confidence": 0.92, "timestamp": ts(40)},
    {"source": "horikita", "target": "hirata",     "type": "ALLIES_WITH",     "weight": 0.75, "trust": 0.72, "confidence": 0.85, "timestamp": ts(8)},
    {"source": "horikita", "target": "sakayanagi", "type": "RIVALS",          "weight": 0.88, "trust": 0.18, "confidence": 0.90, "timestamp": ts(120)},
    {"source": "horikita", "target": "yukimura",   "type": "ALLIES_WITH",     "weight": 0.62, "trust": 0.68, "confidence": 0.80, "timestamp": ts(12)},
    {"source": "horikita", "target": "ichinose",   "type": "ALLIES_WITH",     "weight": 0.58, "trust": 0.62, "confidence": 0.78, "timestamp": ts(55)},
    {"source": "horikita", "target": "chabashira", "type": "DISTRUSTS",       "weight": 0.52, "trust": 0.28, "confidence": 0.75, "timestamp": ts(3)},
    {"source": "horikita", "target": "sato",       "type": "ALLIES_WITH",     "weight": 0.50, "trust": 0.62, "confidence": 0.72, "timestamp": ts(14)},
    {"source": "horikita", "target": "ryuen",      "type": "RIVALS",          "weight": 0.80, "trust": 0.22, "confidence": 0.88, "timestamp": ts(65)},
    # Kushida
    {"source": "kushida", "target": "hirata",     "type": "MANIPULATES",     "weight": 0.82, "trust": 0.32, "confidence": 0.90, "timestamp": ts(7)},
    {"source": "kushida", "target": "horikita",   "type": "DECEIVES",        "weight": 0.92, "trust": 0.08, "confidence": 0.95, "timestamp": ts(38)},
    {"source": "kushida", "target": "sudo",       "type": "MANIPULATES",     "weight": 0.62, "trust": 0.38, "confidence": 0.80, "timestamp": ts(16)},
    {"source": "kushida", "target": "sakura",     "type": "MANIPULATES",     "weight": 0.70, "trust": 0.32, "confidence": 0.85, "timestamp": ts(22)},
    {"source": "kushida", "target": "ryuen",      "type": "INFLUENCES",      "weight": 0.65, "trust": 0.22, "confidence": 0.78, "timestamp": ts(70)},
    {"source": "kushida", "target": "hasebe",     "type": "DECEIVES",        "weight": 0.58, "trust": 0.28, "confidence": 0.75, "timestamp": ts(19)},
    {"source": "kushida", "target": "ichinose",   "type": "INFLUENCES",      "weight": 0.55, "trust": 0.48, "confidence": 0.72, "timestamp": ts(50)},
    {"source": "kushida", "target": "sato",       "type": "MANIPULATES",     "weight": 0.52, "trust": 0.30, "confidence": 0.70, "timestamp": ts(21)},
    # Hirata
    {"source": "hirata", "target": "sudo",       "type": "PROTECTS",         "weight": 0.82, "trust": 0.80, "confidence": 0.90, "timestamp": ts(9)},
    {"source": "hirata", "target": "sakura",     "type": "PROTECTS",         "weight": 0.72, "trust": 0.78, "confidence": 0.85, "timestamp": ts(11)},
    {"source": "hirata", "target": "hasebe",     "type": "ALLIES_WITH",      "weight": 0.68, "trust": 0.72, "confidence": 0.82, "timestamp": ts(7)},
    {"source": "hirata", "target": "koenji",     "type": "DISTRUSTS",        "weight": 0.50, "trust": 0.32, "confidence": 0.70, "timestamp": ts(30)},
    {"source": "hirata", "target": "ichinose",   "type": "ALLIES_WITH",      "weight": 0.62, "trust": 0.72, "confidence": 0.80, "timestamp": ts(55)},
    {"source": "hirata", "target": "yukimura",   "type": "ALLIES_WITH",      "weight": 0.58, "trust": 0.65, "confidence": 0.75, "timestamp": ts(13)},
    # Ryuen
    {"source": "ryuen", "target": "ibuki",      "type": "MANIPULATES",       "weight": 0.92, "trust": 0.52, "confidence": 0.95, "timestamp": ts(4)},
    {"source": "ryuen", "target": "yagami",     "type": "MANIPULATES",       "weight": 0.88, "trust": 0.42, "confidence": 0.92, "timestamp": ts(4)},
    {"source": "ryuen", "target": "albert",     "type": "INFLUENCES",        "weight": 0.82, "trust": 0.58, "confidence": 0.88, "timestamp": ts(4)},
    {"source": "ryuen", "target": "ichinose",   "type": "RIVALS",            "weight": 0.88, "trust": 0.18, "confidence": 0.92, "timestamp": ts(60)},
    {"source": "ryuen", "target": "horikita",   "type": "RIVALS",            "weight": 0.82, "trust": 0.22, "confidence": 0.88, "timestamp": ts(62)},
    {"source": "ryuen", "target": "sakayanagi", "type": "DISTRUSTS",         "weight": 0.72, "trust": 0.28, "confidence": 0.82, "timestamp": ts(95)},
    {"source": "ryuen", "target": "hondou",     "type": "MANIPULATES",       "weight": 0.75, "trust": 0.38, "confidence": 0.85, "timestamp": ts(6)},
    {"source": "ryuen", "target": "kushida",    "type": "ALLIES_WITH",       "weight": 0.62, "trust": 0.28, "confidence": 0.78, "timestamp": ts(72)},
    {"source": "ryuen", "target": "chabashira", "type": "DISTRUSTS",         "weight": 0.50, "trust": 0.22, "confidence": 0.72, "timestamp": ts(30)},
    # Sakayanagi
    {"source": "sakayanagi", "target": "hashimoto",  "type": "MANIPULATES",  "weight": 0.92, "trust": 0.48, "confidence": 0.95, "timestamp": ts(5)},
    {"source": "sakayanagi", "target": "katsuragi",  "type": "RIVALS",       "weight": 0.92, "trust": 0.18, "confidence": 0.95, "timestamp": ts(80)},
    {"source": "sakayanagi", "target": "ayanokoji",  "type": "RIVALS",       "weight": 0.96, "trust": 0.30, "confidence": 0.95, "timestamp": ts(90)},
    {"source": "sakayanagi", "target": "horikita",   "type": "DISTRUSTS",    "weight": 0.78, "trust": 0.18, "confidence": 0.88, "timestamp": ts(125)},
    {"source": "sakayanagi", "target": "nagumo",     "type": "RIVALS",       "weight": 0.82, "trust": 0.22, "confidence": 0.90, "timestamp": ts(185)},
    {"source": "sakayanagi", "target": "kiriyama",   "type": "ALLIES_WITH",  "weight": 0.72, "trust": 0.58, "confidence": 0.82, "timestamp": ts(7)},
    {"source": "sakayanagi", "target": "ichinose",   "type": "RIVALS",       "weight": 0.80, "trust": 0.22, "confidence": 0.88, "timestamp": ts(95)},
    # Ichinose
    {"source": "ichinose", "target": "kanzaki",    "type": "ALLIES_WITH",    "weight": 0.88, "trust": 0.90, "confidence": 0.95, "timestamp": ts(3)},
    {"source": "ichinose", "target": "sakagami",   "type": "ALLIES_WITH",    "weight": 0.82, "trust": 0.86, "confidence": 0.92, "timestamp": ts(3)},
    {"source": "ichinose", "target": "horikita",   "type": "ALLIES_WITH",    "weight": 0.60, "trust": 0.64, "confidence": 0.80, "timestamp": ts(58)},
    {"source": "ichinose", "target": "hirata",     "type": "ALLIES_WITH",    "weight": 0.65, "trust": 0.70, "confidence": 0.82, "timestamp": ts(55)},
    {"source": "ichinose", "target": "ryuen",      "type": "RIVALS",         "weight": 0.78, "trust": 0.22, "confidence": 0.88, "timestamp": ts(62)},
    {"source": "ichinose", "target": "sakayanagi", "type": "DISTRUSTS",      "weight": 0.68, "trust": 0.28, "confidence": 0.80, "timestamp": ts(97)},
    {"source": "ichinose", "target": "nagumo",     "type": "RIVALS",         "weight": 0.72, "trust": 0.18, "confidence": 0.85, "timestamp": ts(188)},
    # Kanzaki
    {"source": "kanzaki", "target": "ichinose",   "type": "PROTECTS",        "weight": 0.88, "trust": 0.92, "confidence": 0.95, "timestamp": ts(3)},
    {"source": "kanzaki", "target": "ryuen",      "type": "RIVALS",          "weight": 0.82, "trust": 0.18, "confidence": 0.90, "timestamp": ts(64)},
    {"source": "kanzaki", "target": "sakayanagi", "type": "DISTRUSTS",       "weight": 0.72, "trust": 0.22, "confidence": 0.82, "timestamp": ts(98)},
    {"source": "kanzaki", "target": "sakagami",   "type": "ALLIES_WITH",     "weight": 0.78, "trust": 0.82, "confidence": 0.88, "timestamp": ts(4)},
    {"source": "kanzaki", "target": "horikita",   "type": "ALLIES_WITH",     "weight": 0.55, "trust": 0.60, "confidence": 0.75, "timestamp": ts(59)},
    # Hashimoto
    {"source": "hashimoto", "target": "sakayanagi", "type": "ALLIES_WITH",   "weight": 0.85, "trust": 0.55, "confidence": 0.90, "timestamp": ts(5)},
    {"source": "hashimoto", "target": "katsuragi",  "type": "RIVALS",        "weight": 0.78, "trust": 0.22, "confidence": 0.85, "timestamp": ts(82)},
    {"source": "hashimoto", "target": "horikita",   "type": "INFLUENCES",    "weight": 0.60, "trust": 0.38, "confidence": 0.78, "timestamp": ts(128)},
    {"source": "hashimoto", "target": "kushida",    "type": "ALLIES_WITH",   "weight": 0.65, "trust": 0.42, "confidence": 0.78, "timestamp": ts(75)},
    {"source": "hashimoto", "target": "kiriyama",   "type": "DISTRUSTS",     "weight": 0.55, "trust": 0.28, "confidence": 0.72, "timestamp": ts(85)},
    # Katsuragi
    {"source": "katsuragi", "target": "sakayanagi", "type": "RIVALS",        "weight": 0.92, "trust": 0.18, "confidence": 0.95, "timestamp": ts(82)},
    {"source": "katsuragi", "target": "hashimoto",  "type": "DISTRUSTS",     "weight": 0.78, "trust": 0.18, "confidence": 0.88, "timestamp": ts(83)},
    {"source": "katsuragi", "target": "kiriyama",   "type": "ALLIES_WITH",   "weight": 0.72, "trust": 0.62, "confidence": 0.82, "timestamp": ts(8)},
    {"source": "katsuragi", "target": "horikita",   "type": "ALLIES_WITH",   "weight": 0.52, "trust": 0.52, "confidence": 0.72, "timestamp": ts(130)},
    # Chabashira
    {"source": "chabashira", "target": "ayanokoji", "type": "INFLUENCES",    "weight": 0.72, "trust": 0.32, "confidence": 0.88, "timestamp": ts(1)},
    {"source": "chabashira", "target": "horikita",  "type": "INFLUENCES",    "weight": 0.62, "trust": 0.42, "confidence": 0.80, "timestamp": ts(2)},
    {"source": "chabashira", "target": "nagumo",    "type": "DISTRUSTS",     "weight": 0.58, "trust": 0.22, "confidence": 0.75, "timestamp": ts(182)},
    # Sudo
    {"source": "sudo", "target": "horikita",   "type": "ALLIES_WITH",        "weight": 0.72, "trust": 0.78, "confidence": 0.88, "timestamp": ts(18)},
    {"source": "sudo", "target": "hirata",     "type": "ALLIES_WITH",        "weight": 0.78, "trust": 0.82, "confidence": 0.88, "timestamp": ts(9)},
    {"source": "sudo", "target": "ryuen",      "type": "RIVALS",             "weight": 0.82, "trust": 0.08, "confidence": 0.90, "timestamp": ts(66)},
    {"source": "sudo", "target": "ibuki",      "type": "RIVALS",             "weight": 0.72, "trust": 0.12, "confidence": 0.85, "timestamp": ts(68)},
    # Sakura
    {"source": "sakura", "target": "ayanokoji", "type": "ALLIES_WITH",       "weight": 0.65, "trust": 0.75, "confidence": 0.80, "timestamp": ts(26)},
    {"source": "sakura", "target": "horikita",  "type": "ALLIES_WITH",       "weight": 0.62, "trust": 0.70, "confidence": 0.78, "timestamp": ts(13)},
    {"source": "sakura", "target": "kushida",   "type": "DISTRUSTS",         "weight": 0.72, "trust": 0.18, "confidence": 0.82, "timestamp": ts(42)},
    {"source": "sakura", "target": "hasebe",    "type": "ALLIES_WITH",       "weight": 0.62, "trust": 0.78, "confidence": 0.80, "timestamp": ts(10)},
    # Hasebe
    {"source": "hasebe", "target": "sakura",   "type": "PROTECTS",           "weight": 0.68, "trust": 0.80, "confidence": 0.85, "timestamp": ts(10)},
    {"source": "hasebe", "target": "horikita", "type": "ALLIES_WITH",        "weight": 0.56, "trust": 0.65, "confidence": 0.75, "timestamp": ts(14)},
    {"source": "hasebe", "target": "sudo",     "type": "ALLIES_WITH",        "weight": 0.62, "trust": 0.70, "confidence": 0.78, "timestamp": ts(20)},
    # Koenji
    {"source": "koenji", "target": "horikita",   "type": "DISTRUSTS",        "weight": 0.52, "trust": 0.18, "confidence": 0.72, "timestamp": ts(30)},
    {"source": "koenji", "target": "sudo",       "type": "RIVALS",           "weight": 0.45, "trust": 0.28, "confidence": 0.68, "timestamp": ts(32)},
    {"source": "koenji", "target": "ayanokoji",  "type": "DISTRUSTS",        "weight": 0.48, "trust": 0.30, "confidence": 0.70, "timestamp": ts(45)},
    {"source": "koenji", "target": "sakayanagi", "type": "RIVALS",           "weight": 0.42, "trust": 0.32, "confidence": 0.65, "timestamp": ts(92)},
    # Ibuki
    {"source": "ibuki", "target": "ryuen",    "type": "ALLIES_WITH",         "weight": 0.82, "trust": 0.62, "confidence": 0.88, "timestamp": ts(5)},
    {"source": "ibuki", "target": "sudo",     "type": "RIVALS",              "weight": 0.78, "trust": 0.12, "confidence": 0.85, "timestamp": ts(68)},
    {"source": "ibuki", "target": "horikita", "type": "RIVALS",              "weight": 0.68, "trust": 0.18, "confidence": 0.80, "timestamp": ts(70)},
    {"source": "ibuki", "target": "albert",   "type": "ALLIES_WITH",         "weight": 0.72, "trust": 0.65, "confidence": 0.82, "timestamp": ts(5)},
    # Yagami
    {"source": "yagami", "target": "ryuen",   "type": "ALLIES_WITH",         "weight": 0.72, "trust": 0.48, "confidence": 0.80, "timestamp": ts(5)},
    {"source": "yagami", "target": "ibuki",   "type": "ALLIES_WITH",         "weight": 0.65, "trust": 0.52, "confidence": 0.78, "timestamp": ts(6)},
    {"source": "yagami", "target": "horikita","type": "DISTRUSTS",           "weight": 0.52, "trust": 0.22, "confidence": 0.72, "timestamp": ts(72)},
    {"source": "yagami", "target": "kushida", "type": "INFLUENCES",          "weight": 0.55, "trust": 0.30, "confidence": 0.72, "timestamp": ts(74)},
    # Nagumo
    {"source": "nagumo", "target": "sakayanagi", "type": "RIVALS",           "weight": 0.88, "trust": 0.22, "confidence": 0.92, "timestamp": ts(185)},
    {"source": "nagumo", "target": "ichinose",   "type": "RIVALS",           "weight": 0.82, "trust": 0.18, "confidence": 0.90, "timestamp": ts(188)},
    {"source": "nagumo", "target": "ayanokoji",  "type": "RIVALS",           "weight": 0.80, "trust": 0.18, "confidence": 0.88, "timestamp": ts(182)},
    {"source": "nagumo", "target": "chabashira", "type": "INFLUENCES",       "weight": 0.62, "trust": 0.32, "confidence": 0.78, "timestamp": ts(183)},
    # Yukimura
    {"source": "yukimura", "target": "horikita",  "type": "ALLIES_WITH",     "weight": 0.65, "trust": 0.70, "confidence": 0.80, "timestamp": ts(12)},
    {"source": "yukimura", "target": "ayanokoji", "type": "DISTRUSTS",       "weight": 0.50, "trust": 0.32, "confidence": 0.70, "timestamp": ts(46)},
    {"source": "yukimura", "target": "sakura",    "type": "ALLIES_WITH",     "weight": 0.55, "trust": 0.65, "confidence": 0.72, "timestamp": ts(14)},
    {"source": "yukimura", "target": "sudo",      "type": "ALLIES_WITH",     "weight": 0.52, "trust": 0.62, "confidence": 0.70, "timestamp": ts(19)},
    # Shiranami
    {"source": "shiranami", "target": "kushida",   "type": "DISTRUSTS",      "weight": 0.72, "trust": 0.12, "confidence": 0.80, "timestamp": ts(43)},
    {"source": "shiranami", "target": "ayanokoji", "type": "INFLUENCES",     "weight": 0.50, "trust": 0.38, "confidence": 0.68, "timestamp": ts(47)},
    {"source": "shiranami", "target": "horikita",  "type": "ALLIES_WITH",    "weight": 0.55, "trust": 0.55, "confidence": 0.72, "timestamp": ts(15)},
    # Albert
    {"source": "albert", "target": "ryuen",  "type": "ALLIES_WITH",          "weight": 0.78, "trust": 0.72, "confidence": 0.88, "timestamp": ts(4)},
    {"source": "albert", "target": "ibuki",  "type": "ALLIES_WITH",          "weight": 0.72, "trust": 0.68, "confidence": 0.85, "timestamp": ts(5)},
    {"source": "albert", "target": "sudo",   "type": "RIVALS",               "weight": 0.68, "trust": 0.18, "confidence": 0.80, "timestamp": ts(67)},
    # Sakagami
    {"source": "sakagami", "target": "ichinose", "type": "PROTECTS",         "weight": 0.82, "trust": 0.86, "confidence": 0.90, "timestamp": ts(3)},
    {"source": "sakagami", "target": "kanzaki",  "type": "ALLIES_WITH",      "weight": 0.78, "trust": 0.82, "confidence": 0.88, "timestamp": ts(4)},
    {"source": "sakagami", "target": "ryuen",    "type": "DISTRUSTS",        "weight": 0.72, "trust": 0.18, "confidence": 0.82, "timestamp": ts(63)},
    # Sato
    {"source": "sato", "target": "horikita",   "type": "ALLIES_WITH",        "weight": 0.55, "trust": 0.65, "confidence": 0.72, "timestamp": ts(15)},
    {"source": "sato", "target": "ayanokoji",  "type": "ALLIES_WITH",        "weight": 0.60, "trust": 0.68, "confidence": 0.75, "timestamp": ts(27)},
    {"source": "sato", "target": "kushida",    "type": "DISTRUSTS",          "weight": 0.62, "trust": 0.28, "confidence": 0.75, "timestamp": ts(44)},
    {"source": "sato", "target": "hirata",     "type": "ALLIES_WITH",        "weight": 0.58, "trust": 0.70, "confidence": 0.72, "timestamp": ts(10)},
    # Hondou
    {"source": "hondou", "target": "ryuen",    "type": "DISTRUSTS",          "weight": 0.62, "trust": 0.32, "confidence": 0.75, "timestamp": ts(100)},
    {"source": "hondou", "target": "ibuki",    "type": "ALLIES_WITH",        "weight": 0.55, "trust": 0.50, "confidence": 0.70, "timestamp": ts(6)},
    {"source": "hondou", "target": "ichinose", "type": "INFLUENCES",         "weight": 0.45, "trust": 0.55, "confidence": 0.65, "timestamp": ts(101)},
    # Kiriyama
    {"source": "kiriyama", "target": "sakayanagi", "type": "ALLIES_WITH",    "weight": 0.75, "trust": 0.62, "confidence": 0.82, "timestamp": ts(7)},
    {"source": "kiriyama", "target": "katsuragi",  "type": "ALLIES_WITH",    "weight": 0.72, "trust": 0.60, "confidence": 0.80, "timestamp": ts(8)},
    {"source": "kiriyama", "target": "hashimoto",  "type": "DISTRUSTS",      "weight": 0.58, "trust": 0.28, "confidence": 0.72, "timestamp": ts(86)},
]

EVENTS = [
    {"id": "ev_001", "title": "Class Formation", "description": "Students assigned to classes. Point distribution reveals the system's brutal hierarchy.", "season": 1, "day_offset": 0, "affected_characters": ["ayanokoji","horikita","kushida","hirata","sudo"]},
    {"id": "ev_002", "title": "Pool Incident", "description": "Sudo accused of assault by Class C. Ayanokoji secretly orchestrates his defense.", "season": 1, "day_offset": 45, "affected_characters": ["sudo","ryuen","ayanokoji","horikita"]},
    {"id": "ev_003", "title": "Deserted Island Exam", "description": "Inter-class survival exam. Hidden alliances form under pressure. Kushida's true nature glimpsed.", "season": 1, "day_offset": 88, "affected_characters": ["ayanokoji","kushida","horikita","ryuen","ichinose"]},
    {"id": "ev_004", "title": "Kushida's Secret Exposed", "description": "Ayanokoji discovers Kushida's dark persona. Mutual blackmail established.", "season": 1, "day_offset": 120, "affected_characters": ["ayanokoji","kushida"]},
    {"id": "ev_005", "title": "Sports Festival", "description": "Class rivalries erupt. Ayanokoji demonstrates controlled capability. Ryuen targets Class D.", "season": 2, "day_offset": 175, "affected_characters": ["ayanokoji","ryuen","horikita","sudo","sakayanagi"]},
    {"id": "ev_006", "title": "Ryuen's Assault on Ibuki", "description": "Ryuen disciplines Ibuki after failure. Her loyalty fractures silently.", "season": 2, "day_offset": 210, "affected_characters": ["ryuen","ibuki"]},
    {"id": "ev_007", "title": "Horikita's Leadership Rise", "description": "Horikita takes official leadership of Class D. Power structure shifts.", "season": 2, "day_offset": 268, "affected_characters": ["horikita","hirata","sudo","kushida"]},
    {"id": "ev_008", "title": "Class C Fracture", "description": "Hondou begins questioning Ryuen's methods. Subtle defection risk emerges.", "season": 2, "day_offset": 295, "affected_characters": ["hondou","ryuen","ibuki"]},
    {"id": "ev_009", "title": "Sakayanagi's Gambit", "description": "Sakayanagi moves against Katsuragi faction. Class A internal war begins.", "season": 3, "day_offset": 355, "affected_characters": ["sakayanagi","katsuragi","hashimoto","kiriyama"]},
    {"id": "ev_010", "title": "Nagumo Assumes Control", "description": "Nagumo consolidates Student Council power. Institutional pressure on all classes intensifies.", "season": 3, "day_offset": 388, "affected_characters": ["nagumo","ichinose","sakayanagi","chabashira"]},
    {"id": "ev_011", "title": "White Room Revelation", "description": "Chabashira reveals partial knowledge of Ayanokoji's origin to him privately.", "season": 3, "day_offset": 420, "affected_characters": ["ayanokoji","chabashira"]},
    {"id": "ev_012", "title": "Final Semester Exam", "description": "All-class strategic confrontation. Hidden alliances determine class rankings.", "season": 3, "day_offset": 450, "affected_characters": ["ayanokoji","horikita","ryuen","sakayanagi","ichinose","nagumo"]},
]
